name: stormtune
description: StormTune - Smart Racing Tuning Recommendations
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  geolocator: ^10.1.0
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  sqlite3_flutter_libs: ^0.5.0
  sqlite3: ^2.3.0
  path: ^1.8.3
  provider: ^6.1.1
  flutter_secure_storage: ^9.0.0
  permission_handler: ^11.0.1
  geocoding: ^2.1.1
  intl: ^0.18.1
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/logo.png

flutter_launcher_icons:
  android: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/logo.png"
